# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

dist: ./dist

git:
  tag_sort: smartsemver

project_name: "renovate-exporter"

before:
  hooks:
    - go mod tidy

builds:
  - id: "exporter"
    main: .
    binary: renovate-exporter
    goos: [linux]
    goarch: [amd64]

archives:
  - id: "archive"
    ids:
      - "exporter"
    formats: [tar.gz]

release:
  prerelease: auto

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
